/**
 * TaskFlow — Transactional Task Manager (Modern Formal Edition)
 *
 * Concept: Users create, read, update, and delete task records via REST API.
 * Each task is a transaction stored on the server (JSON Server).
 *
 * Task data model:
 *   id          — number (generated by server)
 *   title       — string (required)
 *   description — string (optional)
 *   priority    — low | medium | high
 *   status      — pending | in-progress | done
 *   dueDate     — string (ISO date YYYY-MM-DD)
 */

// ---------------------------------------------------------------------------
// Task model constants
// ---------------------------------------------------------------------------

const PRIORITY_VALUES = ['low', 'medium', 'high'];
const STATUS_VALUES = ['pending', 'in-progress', 'done'];
const STATUS_CYCLE = ['pending', 'in-progress', 'done'];

// Use local JSON Server when testing on your machine; otherwise use hosted read API.
const API =
  window.location.hostname === 'localhost' ||
  window.location.hostname === '127.0.0.1'
    ? 'http://localhost:3000/tasks'
    : 'https://my-json-server.typicode.com/dulutancarlo1975/taskflow/tasks';

function usesPersistedApi() {
  return API.includes('localhost') || API.includes('127.0.0.1');
}

// ---------------------------------------------------------------------------
// State
// ---------------------------------------------------------------------------

let tasks = [];
let editingId = null;
let currentFilter = 'all';

// ---------------------------------------------------------------------------
// DOM references
// ---------------------------------------------------------------------------

const form = document.getElementById('task-form');
const list = document.getElementById('task-list');
const errorEl = document.getElementById('error-msg');
const loadingEl = document.getElementById('loading-indicator');
const submitBtn = document.getElementById('submit-btn');
const cancelEditBtn = document.getElementById('cancel-edit-btn');
const formHeading = document.getElementById('form-heading');
const taskCountEl = document.getElementById('task-count');
const clearDoneBtn = document.getElementById('clear-done-btn');
const filterButtons = document.querySelectorAll('.filter-btn');

// ---------------------------------------------------------------------------
// Task model helpers
// ---------------------------------------------------------------------------

function normalizeTask(raw) {
  return {
    id: raw.id,
    title: String(raw.title || '').trim(),
    description: String(raw.description || '').trim(),
    priority: PRIORITY_VALUES.includes(raw.priority) ? raw.priority : 'medium',
    status: STATUS_VALUES.includes(raw.status) ? raw.status : 'pending',
    dueDate: raw.dueDate || ''
  };
}

function buildTaskFromForm(values, id) {
  const task = {
    title: values.title,
    description: values.description,
    priority: values.priority,
    status: values.status,
    dueDate: values.dueDate
  };
  if (id !== null && id !== undefined) {
    task.id = id;
  }
  return task;
}

function validateTaskInput(values) {
  if (!values.title.trim()) {
    showError('Title is required. Please enter a task title.');
    return false;
  }
  if (!PRIORITY_VALUES.includes(values.priority)) {
    showError('Priority must be low, medium, or high.');
    return false;
  }
  if (!STATUS_VALUES.includes(values.status)) {
    showError('Status must be pending, in-progress, or done.');
    return false;
  }
  return true;
}

function getFilteredTasks() {
  if (currentFilter === 'all') {
    return tasks;
  }
  return tasks.filter(function matchStatus(task) {
    return task.status === currentFilter;
  });
}

function nextStatus(current) {
  const index = STATUS_CYCLE.indexOf(current);
  if (index === -1) {
    return 'pending';
  }
  return STATUS_CYCLE[(index + 1) % STATUS_CYCLE.length];
}

// ---------------------------------------------------------------------------
// UI helpers
// ---------------------------------------------------------------------------

function showError(message) {
  errorEl.textContent = message;
  errorEl.hidden = false;
  setTimeout(function clearErrorMessage() {
    errorEl.textContent = '';
    errorEl.hidden = true;
  }, 4000);
}

function showLoading(isLoading) {
  loadingEl.hidden = !isLoading;
  if (isLoading) {
    list.innerHTML = '';
    taskCountEl.textContent = '';
  }
}

function showEmptyState() {
  list.innerHTML = '';
  const empty = document.createElement('li');
  empty.className = 'empty-state';
  empty.setAttribute('role', 'status');

  if (currentFilter === 'all') {
    empty.innerHTML =
      '<p>No tasks yet.</p><p>Add a task using the form — it will be saved to the server.</p>';
  } else {
    empty.innerHTML =
      '<p>No tasks in this view.</p><p>Try another filter or add a new task.</p>';
  }
  list.appendChild(empty);
}

function updateTaskCount() {
  const visible = getFilteredTasks().length;
  const total = tasks.length;
  const doneCount = tasks.filter(function isDone(t) {
    return t.status === 'done';
  }).length;

  if (total === 0) {
    taskCountEl.textContent = 'No tasks in the database.';
    clearDoneBtn.disabled = true;
    return;
  }

  clearDoneBtn.disabled = doneCount === 0;

  if (currentFilter === 'all') {
    taskCountEl.textContent =
      visible + ' task' + (visible === 1 ? '' : 's') + ' · ' + doneCount + ' completed';
  } else {
    taskCountEl.textContent =
      visible + ' of ' + total + ' task' + (total === 1 ? '' : 's') + ' shown';
  }
}

function formatStatusLabel(status) {
  if (status === 'in-progress') {
    return 'In Progress';
  }
  return status.charAt(0).toUpperCase() + status.slice(1);
}

function statusBadgeClass(status) {
  if (status === 'in-progress') {
    return 'badge-status-in-progress';
  }
  return 'badge-status-' + status;
}

function setActiveFilter(filter) {
  currentFilter = filter;
  filterButtons.forEach(function updateBtn(btn) {
    btn.classList.toggle('is-active', btn.dataset.filter === filter);
  });
  renderTasks();
}

// ---------------------------------------------------------------------------
// Form
// ---------------------------------------------------------------------------

function readFormValues() {
  return {
    title: document.getElementById('title').value.trim(),
    description: document.getElementById('description').value.trim(),
    priority: document.getElementById('priority').value,
    status: document.getElementById('status').value,
    dueDate: document.getElementById('dueDate').value
  };
}

function populateForm(task) {
  document.getElementById('title').value = task.title;
  document.getElementById('description').value = task.description || '';
  document.getElementById('priority').value = task.priority;
  document.getElementById('status').value = task.status;
  document.getElementById('dueDate').value = task.dueDate || '';
}

function enterEditMode(task) {
  editingId = task.id;
  populateForm(task);
  submitBtn.textContent = 'Update Task';
  cancelEditBtn.hidden = false;
  formHeading.textContent = 'Edit Transaction';
  document.getElementById('title').focus();
}

function exitEditMode() {
  editingId = null;
  form.reset();
  submitBtn.textContent = 'Add Task';
  cancelEditBtn.hidden = true;
  formHeading.textContent = 'Create Transaction';
}

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

function createTaskCard(task) {
  const li = document.createElement('li');
  li.className = 'task-card ' + task.priority + (task.status === 'done' ? ' is-done' : '');
  li.dataset.id = String(task.id);

  const header = document.createElement('div');
  header.className = 'task-card-header';

  const titleEl = document.createElement('h3');
  titleEl.className = 'task-card-title';
  titleEl.textContent = task.title;
  header.appendChild(titleEl);

  const idEl = document.createElement('span');
  idEl.className = 'task-id';
  idEl.textContent = '#' + task.id;
  header.appendChild(idEl);
  li.appendChild(header);

  if (task.description) {
    const desc = document.createElement('p');
    desc.className = 'task-card-description';
    desc.textContent = task.description;
    li.appendChild(desc);
  }

  const meta = document.createElement('div');
  meta.className = 'task-meta';

  const priorityBadge = document.createElement('span');
  priorityBadge.className = 'badge badge-priority';
  priorityBadge.textContent = task.priority;
  meta.appendChild(priorityBadge);

  const statusBadge = document.createElement('span');
  statusBadge.className = 'badge ' + statusBadgeClass(task.status);
  statusBadge.textContent = formatStatusLabel(task.status);
  meta.appendChild(statusBadge);

  if (task.dueDate) {
    const due = document.createElement('span');
    due.className = 'task-due';
    due.textContent = 'Due: ' + task.dueDate;
    meta.appendChild(due);
  }

  li.appendChild(meta);

  const actions = document.createElement('div');
  actions.className = 'task-actions';

  const toggleBtn = document.createElement('button');
  toggleBtn.type = 'button';
  toggleBtn.className = 'btn-toggle';
  toggleBtn.textContent = 'Toggle Status';
  toggleBtn.addEventListener('click', function handleToggleClick() {
    handleToggleStatus(task);
  });
  actions.appendChild(toggleBtn);

  const editBtn = document.createElement('button');
  editBtn.type = 'button';
  editBtn.className = 'btn-edit';
  editBtn.textContent = 'Edit';
  editBtn.addEventListener('click', function handleEditClick() {
    handleEdit(task);
  });
  actions.appendChild(editBtn);

  const deleteBtn = document.createElement('button');
  deleteBtn.type = 'button';
  deleteBtn.className = 'btn-delete';
  deleteBtn.textContent = 'Delete';
  deleteBtn.addEventListener('click', function handleDeleteClick() {
    handleDelete(task.id);
  });
  actions.appendChild(deleteBtn);

  li.appendChild(actions);
  return li;
}

function renderTasks() {
  list.innerHTML = '';
  const visible = getFilteredTasks();
  updateTaskCount();

  if (visible.length === 0) {
    showEmptyState();
    return;
  }

  visible.forEach(function appendTaskCard(task) {
    list.appendChild(createTaskCard(task));
  });
}

// ---------------------------------------------------------------------------
// Event handlers
// ---------------------------------------------------------------------------

function handleEdit(task) {
  enterEditMode(task);
}

function handleToggleStatus(task) {
  const updatedObj = buildTaskFromForm(
    Object.assign({}, task, { status: nextStatus(task.status) }),
    task.id
  );
  updateTask(task.id, updatedObj);
}

function handleDelete(id) {
  if (!window.confirm('Delete this task from the server?')) {
    return;
  }
  deleteTask(id);
}

async function handleClearCompleted() {
  const doneTasks = tasks.filter(function isDone(t) {
    return t.status === 'done';
  });

  if (doneTasks.length === 0) {
    showError('No completed tasks to delete.');
    return;
  }

  if (
    !window.confirm(
      'Delete ' + doneTasks.length + ' completed task(s) from the server?'
    )
  ) {
    return;
  }

  try {
    showLoading(true);
    for (const task of doneTasks) {
      const res = await fetch(API + '/' + task.id, { method: 'DELETE' });
      if (!res.ok) throw new Error('Failed to delete task #' + task.id);
    }
    if (usesPersistedApi()) {
      await loadTasks();
    } else {
      const doneIds = new Set(doneTasks.map(function getId(t) { return t.id; }));
      tasks = tasks.filter(function notDone(t) { return !doneIds.has(t.id); });
      renderTasks();
      showLoading(false);
    }
  } catch (err) {
    showError(err.message);
    showLoading(false);
    renderTasks();
  }
}

async function handleFormSubmit(event) {
  event.preventDefault();
  const values = readFormValues();

  if (!validateTaskInput(values)) {
    return;
  }

  if (editingId !== null) {
    const updatedObj = buildTaskFromForm(values, editingId);
    const updated = await updateTask(editingId, updatedObj);
    if (updated) {
      exitEditMode();
    }
    return;
  }

  const taskObj = buildTaskFromForm(values);
  const created = await addTask(taskObj);
  if (created) {
    form.reset();
  }
}

function handleCancelEdit() {
  exitEditMode();
}

// ---------------------------------------------------------------------------
// API — CRUD
// ---------------------------------------------------------------------------

async function loadTasks() {
  try {
    showLoading(true);
    const res = await fetch(API);
    if (!res.ok) throw new Error('Failed to load tasks');
    const data = await res.json();
    tasks = data.map(normalizeTask);
    renderTasks();
  } catch (err) {
    showError(err.message);
    if (tasks.length === 0) {
      showEmptyState();
    } else {
      renderTasks();
    }
  } finally {
    showLoading(false);
  }
}

async function addTask(taskObj) {
  try {
    const res = await fetch(API, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(taskObj)
    });
    if (!res.ok) throw new Error('Failed to create task');
    if (usesPersistedApi()) {
      await loadTasks();
    } else {
      const created = await res.json();
      tasks.push(normalizeTask(created));
      renderTasks();
    }
    return true;
  } catch (err) {
    showError(err.message);
    return false;
  }
}

async function updateTask(id, updatedObj) {
  try {
    const res = await fetch(API + '/' + id, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(updatedObj)
    });
    if (!res.ok) throw new Error('Failed to update task');
    if (usesPersistedApi()) {
      await loadTasks();
    } else {
      const updated = await res.json();
      const index = tasks.findIndex(function matchId(t) { return t.id === id; });
      if (index !== -1) {
        tasks[index] = normalizeTask(updated);
      }
      renderTasks();
    }
    return true;
  } catch (err) {
    showError(err.message);
    return false;
  }
}

async function deleteTask(id) {
  try {
    const res = await fetch(API + '/' + id, { method: 'DELETE' });
    if (!res.ok) throw new Error('Failed to delete task');
    if (usesPersistedApi()) {
      await loadTasks();
    } else {
      tasks = tasks.filter(function keepTask(t) { return t.id !== id; });
      renderTasks();
    }
    return true;
  } catch (err) {
    showError(err.message);
    return false;
  }
}

// ---------------------------------------------------------------------------
// Initialization
// ---------------------------------------------------------------------------

form.addEventListener('submit', handleFormSubmit);
cancelEditBtn.addEventListener('click', handleCancelEdit);
clearDoneBtn.addEventListener('click', handleClearCompleted);

filterButtons.forEach(function bindFilter(btn) {
  btn.addEventListener('click', function onFilterClick() {
    setActiveFilter(btn.dataset.filter);
  });
});

document.addEventListener('DOMContentLoaded', loadTasks);
